---
- name: redhat | installing base packages
  yum:
    name: "{{ base_redhat_packages }}"
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | installing base packages
  dnf:
    name: "{{ base_redhat_packages }}"
    state: present
  become: true
  when: ansible_distribution == "Fedora"
